server:
  port: 8769

spring:
  application:
    name: repeater-server
  datasource:
    url: jdbc:mysql://192.168.200.154:3306/repeater2?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: jRoQ#BF%P4IN
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  data:
    elasticsearch:
      cluster-name: jvm-sandbox-elasticsearch
      cluster-nodes: 192.168.200.165:9200
      repositories:
        enabled: true
mybatis:
  type-aliases-package: com.alibaba.repeater.console.dal.model

console:
  use:
    localCache: false
repeat:
  # repeater 供 repeater-console 调用的推送回放任务接口
  repeat:
    url: http://192.168.70.189:8002/sandbox/default/module/http/repeater/repeat
  # repeater 供 repeater-console 调用的更新配置接口
  config:
    url: http://192.168.70.189:8002/sandbox/default/module/http/repeater/pushConfig
  # repeater 供 repeater-console 调用的重载刷新接口
  reload:
    url: http://192.168.70.189:8002/sandbox/default/module/http/repeater/reload
  # 冻结
active:
  uri: http://192.168.70.189:8002/sandbox/default/module/http/sandbox-module-mgr/active?ids=repeater
  # 解冻
frozen:
  uri: http://192.168.70.189:8002/sandbox/default/module/http/sandbox-module-mgr/frozen?ids=repeater
